baseURL = "http://self-contained.netlify.app/"
languageCode = "en-us"
title = "Self Contained Gardens"
theme = "ananke"

resourceDir = "../resources"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = ""
  favicon = ""
  site_logo = ""
  description = "Small space garden design"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/https://res.cloudinary.com/djd5xu1es/image/upload/v1639133957/desnlow-oz-banner_hdpxne.jpg"
  recent_posts_number = 4

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
